local yaml = require('lyaml')

local home = require 'os'.getenv('HOME')
_G.neovim_config = yaml.load(io.open("config.yaml"):read("*a"))

require('plugins')
require('theme').setup()
require('util.helpers')
require('core.settings')
require('keybindings.general')
require('lsp.lsp')
require('globals.globals')
require('documentation.loadDocumentation')
require('extensions')
require('debugging.dap')
