local yaml = require('lyaml')

local config = io.open("config.yaml"):read("*a")
_G.neovim_config = yaml.load(config)

require('plugins')
require('theme').setup()
require('util.helpers')
require('core.settings')
require('keybindings.general')
require('lsp.lsp')
require('globals.globals')
require('documentation.loadDocumentation')
require('extensions')
require('debugging.dap')
